---
name: build
on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-java-source:
    name: build jar file
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java build environmant
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn package

      - name: Upload jar file
        uses: actions/upload-artifact@v3
        with:
          name: authentication_lib.jar
          path: target/authentication_lib.jar
