name: Release draft creation

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: get latest release with tag
      id: latestrelease
      run: |
          echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/OCTRI/authentication-lib/releases/latest | jq '.tag_name' | sed 's/\"//g')"
    
    - name: confirm release tag
      run: |
          echo ${{ steps.latestrelease.outputs.releasetag }}
    
    - name: tagcheckout
      uses: actions/checkout@v4
      with:
          ref: ${{ steps.latestrelease.outputs.releasetag }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
    
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}